# Generated by Django 3.2.18 on 2024-04-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('bank_nm', models.CharField(help_text='Bank Name', max_length=20)),
                ('account_nm', models.CharField(help_text='Account Number', max_length=20)),
                ('ifsc_code', models.CharField(help_text='IFSC Number', max_length=20)),
                ('branch', models.CharField(help_text='Branch', max_length=20)),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
    ]
